##      - name: test-version-changed
####        stage: test
##        shell: bash
##        run: git diff --exit-code VERSION
##
##
##      - name: release-inc-patch
####        stage: deploy
####        image: python:3.7.6-slim-buster
####        caches:
####          - pip
##        shell: bash
##        run: ./Scripts/release.sh patch
####          - apt-get update && apt-get install -y git
####          - pip install fire==0.2.1
####        when: manual
####        only:
####          - master
##
##      - name: release-inc-minor
####        stage: deploy
####        image: python:3.7.6-slim-buster
####        caches:
####          - pip
##        shell: bash
##        run: ./Scripts/release.sh minor
####          - apt-get update && apt-get install -y git
####          - pip install fire==0.2.1
####        when: manual
####        only:
####          - master
##
##      - name: release-inc-major
####        stage: deploy
####        image: python:3.7.6-slim-buster
####        caches:
####          - pip
##        shell: bash
##        run: ./Scripts/release.sh major
####          - apt-get update && apt-get install -y git
####          - pip install fire==0.2.1
####        when: manual
####        only:
####          - master
